### ISSUE TITLE
laravel worker

### ISSUE THREAD

**Issue by diogofm7** [kool-dev/docker-php#34]
Functionality to run laravel worker and scheduler could be added.

**Comment by fabriciojs** [comment]
Hello @diogofm7 ! Thanks for creating this issue.

Please can you elaborate a bit on what you imagine such a feature would look like?

What we usually do is having a second service on `docker-compose.yml` (second container) specifically running the command `command: [ php, artisan, horizon ]` for example... thus creating a new daemon service container to whatever we need.

I am not sure what we could do to better support this at the image-level, in this repo.

Cheers
