### ISSUE TITLE
github action running as root

### ISSUE THREAD

**Issue by diogofm7** [kool-dev/docker-php#35]
Good evening,
I have a very strange problem, I don't know if anyone has been through this...

when right on my server via putty, and I run "kool exec app id -u" it returns 1001 which is the correct kool user of the container.

however when I run this same command via gitHubAction, it returns 0, showing that I ran the command as root.

Does anyone know what it can be?

workflows/master.yml
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /docker/kool_test
            kool exec app id -u

**Comment by fabriciojs** [comment]
Hello @diogofm7 

If I understand correctly what you are trying to say, the script `cd /docker/kool_test; kool exec app id -u` is executed on your server, through an SSH session with user `${{ secrets.SSH_USER }}`, correct?

Please can you do two things and bring us the result for analysis (please obfuscate in case anything sensible for you is present in the output):

1. Add to your script `id -u`, so we confirm what user you are in that SSH session bash.
2. Change the `kool` command to be `kool --verbose exec app id -u` (adding the `--verbose` flag will output the Docker commands being used).

Also, via Putty right in the server, could you grab both outputs as well? your `id -u` and `kool --verbose exec app id -u`.

With that I believe we will be able to understand what is going on. My hunch is that either you are running different users, or simply the non-TTY SSH session from the GH action is not filling in all environment variables `kool` uses to determine the running user ID.

Other than that, is important to confirm - what user did you do `kool start` with? That should be the non-root user as well, important to confirm that.

**Comment by diogofm7** [comment]
> Hello @diogofm7
> 
> If I understand correctly what you are trying to say, the script `cd /docker/kool_test; kool exec app id -u` is executed on your server, through an SSH session with user `${{ secrets.SSH_USER }}`, correct?
> 
> Please can you do two things and bring us the result for analysis (please obfuscate in case anything sensible for you is present in the output):
> 
> 1. Add to your script `id -u`, so we confirm what user you are in that SSH session bash.
> 2. Change the `kool` command to be `kool --verbose exec app id -u` (adding the `--verbose` flag will output the Docker commands being used).
> 
> Also, via Putty right in the server, could you grab both outputs as well? your `id -u` and `kool --verbose exec app id -u`.
> 
> With that I believe we will be able to understand what is going on. My hunch is that either you are running different users, or simply the non-TTY SSH session from the GH action is not filling in all environment variables `kool` uses to determine the running user ID.
> 
> Other than that, is important to confirm - what user did you do `kool start` with? That should be the non-root user as well, important to confirm that.

Putty:
![image](https://user-images.githubusercontent.com/33474923/128546032-4d769308-f285-478d-8eb1-12e6ebbb840c.png)

GitHubAction:
![image](https://user-images.githubusercontent.com/33474923/128546117-0ab4cf35-2e11-4d20-a72a-732a9b452150.png)


out: 1001 is the userid logged by GitHub Action...

I noticed that GitHub Action doesn't fill the "--user 1001".

Kool start was run by user ubuntu (id: 1001)

**Comment by fabriciojs** [comment]
@diogofm7 thank you for all information.

A quick test/workaround:  can you try, on the GH action script, running `export UID=$(id -u)` before calling the `kool exec` command? Let us know if that works.

---

Reasoning:

So indeed it is something off with the way the non-TTY SSH session is running and how the `kool` CLI attempts to determine the `UID` of the user.

`kool` CLI on Linux will rely on Golang `os.Getuid()` (https://github.com/kool-dev/kool/blob/d7603ed72ac7948d8b53336b7baf0a5eabc71645/core/environment/uid.go#L17)

The proposed workaround is trying to define the UID environment variable ourselves, this way `kool` should then know the correct user based on that variable.

**Comment by diogofm7** [comment]
> @ diogofm7 obrigado por todas as informações.
> 
> Um teste / solução alternativa rápida: você pode tentar, no script de ação do GH, executar `export UID=$(id -u)`antes de chamar o `kool exec`comando? Deixe-nos saber se isso funciona.
> 
> Raciocínio:
> 
> Então, de fato, é algo errado com a maneira como a sessão SSH não-TTY está sendo executada e como a `kool`CLI tenta determinar o `UID`do usuário.
> 
> `kool`CLI no Linux dependerá do Golang `os.Getuid()`( https://github.com/kool-dev/kool/blob/d7603ed72ac7948d8b53336b7baf0a5eabc71645/core/environment/uid.go#L17 )
> 
> A solução proposta é tentar definir a variável de ambiente UID nós mesmos, desta forma, `kool`devemos saber o usuário correto com base nessa variável.

![image](https://user-images.githubusercontent.com/33474923/128550983-9a35efef-3e11-4b03-a8cd-8e4e0b1ed7f6.png)

**Comment by fabriciojs** [comment]
Aha, my bad... that error is correct, we can't change that variable... but that is even weirder, it means that the variable is already defined! and apparently, to 0??

Well @diogofm7 given that now you can change a different, Kool specific variable:

```
export KOOL_ASUSER=$(id -u)
```

Reasoning:

The variable `KOOL_ASUSER` has precedence, and being a Kool-specific variable you certainly will be able to write it.

https://github.com/kool-dev/kool/blob/d7603ed72ac7948d8b53336b7baf0a5eabc71645/core/environment/asuser.go#L7

This now should "fix" your situation, but I am still puzzled on why it could not solve the UID properly by default... 

After this works, please could you provide the output of `env` command on that SSH session on the GH action? You should obfuscate any sensible information that included in the output, in case of any).

**Comment by diogofm7** [comment]
> export KOOL_ASUSER=$(id -u)

![image](https://user-images.githubusercontent.com/33474923/128553912-924ec0b9-2958-4a16-b36c-fdd19d502bca.png)

**Comment by fabriciojs** [comment]
@diogofm7 well, that doesn't make any sense based on the CLI logic, as far as I following... we would need to investigate further why that is happening.

I advise:

- keep the `--verbose` with this latest test, to confirm that the `--user 1001` is not being passed down.
- double-check again that `id -u` is really outputting `1001` even from the SSH session on the GH action.
- for easier communication on this kind of support - please can you join our Slack? There is a `support`  and even a `support-ptbr` channels there, so will be better to communicate than here.

You can join our Slack on this link:  https://kool.dev/slack

Cheers

**Comment by fabriciojs** [comment]
@diogofm7 I am closing this, it is fixed now since [latest `1.13.1` release](https://github.com/kool-dev/kool/releases/tag/1.13.1). (https://github.com/kool-dev/kool/pull/364)
