### ISSUE TITLE
What's the recommended way of installing and enabling php extensions?

### ISSUE THREAD

**Issue by lpanebr** [kool-dev/docker-php#36]
I'm getting the following composer errors:
```bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires PHP extension ext-gmp * but it is missing from your system. Install or enable PHP's gmp extension.
  Problem 2
    - Root composer.json requires PHP extension ext-memcached * but it is missing from your system. Install or enable PHP's memcached extension.
  Problem 3
    - Root composer.json requires PHP extension ext-zend-opcache * but it is missing from your system. Install or enable PHP's zend-opcache extension.   
```

**So I'd like know what's the proper recommended way to fix?**

**Comment by dbpolito** [comment]
Hey, the way to go would be:

at your `docker-compose.yml`  file, you need to change this part:

```yaml
  # from
  app:
    image: kooldev/php:7.4-nginx

  # to
  app:
    build: .
```

Then you need to create a file `Dockerfile` with something like:

```dockerfile
FROM kooldev/php:8.0-nginx # or the image you chose

# and all your customizations here
```

Then every time you change the dockerfile you need to run `kool start --rebuild`

You can see how image was build here:

https://github.com/kool-dev/docker-php/blob/master/8.0/Dockerfile
https://github.com/kool-dev/docker-php/blob/master/8.0-nginx/Dockerfile

**Comment by lpanebr** [comment]
Thank you!

**Comment by fabriciojs** [comment]
@lpanebr I am closing this as the answer seemed to be satisfactory for your question! We eventually will gather this kind of content when improving and expanding our documentation.

If you have any other questions please feel free to reach out.
