### ISSUE TITLE
Feature Request: MySQLi Driver Extension

### ISSUE THREAD

**Issue by ajmeireles** [kool-dev/docker-php#38]
Hello!

To use the newly added preset of CodeIgniter 4 at kool.dev it is necessary that the MySQLi driver is available. For that, I created a PR in order to provision the adjustment by adding this driver. You can check the PR at this link: https://github.com/kool-dev/docker-php/pull/37

**Comment by fabriciojs** [comment]
The PR has been merged, thank you!
