### ISSUE TITLE
upgrade for php 8.1 image kooldev/php:8.0-nginx

### ISSUE THREAD

**Issue by gabrielzona23** [kool-dev/docker-php#42]
Do you intend to create a version of your docker with nginx in version 8.1 of php?

**Comment by fabriciojs** [comment]
Hey @gabrielzona23 

Yes, we definitely intend to have it as soon as possible.
 
Any help is highly appreciated - I hope to have this by the end of this week.

**Comment by gabrielzona23** [comment]
Thank you very much for your attention @fabriciojs 

Looking forward to the new version!

**Comment by fabriciojs** [comment]
hey @gabrielzona23 

we have now built and tagged the images with PHP 8.1. And also we have released a new `kool` version (https://github.com/kool-dev/kool/releases/tag/1.16.0) that will already have the option to preset/create projects using PHP 8.1.

Closing this issue now. Let us know if you run into any trouble using the new images!
