### ISSUE TITLE
Remover composer2 das imagens do PHP

### ISSUE THREAD

**Issue by zarpelon** [kool-dev/docker-php#59]
Durante a transição das versões de composer, foi adicionado como paliativo um alias chamado composer2 onde era instalado a versão mais recente do composer porém mantendo a primeira na imagem.

Sugiro caso não haja mais necessidade nas novas imagens que seja removido.

![image](https://user-images.githubusercontent.com/264762/181814097-802e4bbe-5299-42b1-b10e-8e1297536f1b.png)

**Comment by fabriciojs** [comment]
Removed 👍🏻
