### ISSUE TITLE
Add support for SSL setup on Nginx images

### ISSUE THREAD

**Issue by fabriciojs** [kool-dev/docker-php#6]
How can I add SSL support on my Nginx running images? Is there an example of configuration file I can override? How does that work on top of `dockerize` template changes?

I guess would be great to have some simple environment variable injection we could do to setup SSL on Nginx. (this will be helpful as well when we work on getting some implementation for https://github.com/kool-dev/kool/issues/28).

**Comment by erhan-data** [comment]
Hi @fabriciojs,

when you guys have plan to implement this feature. Now a days it is kind of crucial. 

Cheers.

**Comment by fabriciojs** [comment]
Hello @erhan-data !

Yes, we definitely aim to add this. I imagine having some environment variable enabling SSL and then pointing to the mapped certificates.

A more elaborated and better DX scenario would be having a helper for `certbot` as well... but that needs some more planning.

**Comment by lucassmacedo** [comment]
Hi guys, any planning of have a SSL support?

**Comment by fabriciojs** [comment]
Hey @lucassmacedo - working on a solution candidate for a project needs - if you want to follow closely - we may merge/add this very soon.

PR: https://github.com/kool-dev/docker-php/pull/76
